// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjPlatinaSteam.Data;

#nullable disable

namespace ProjPlatinaSteam.Migrations
{
    [DbContext(typeof(PlatinaSteamContext))]
    [Migration("20260223223508_AdicionandoIsAdminII")]
    partial class AdicionandoIsAdminII
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjPlatinaSteam.Models.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<string>("apiNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("conquistada")
                        .HasColumnType("bit");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ehDLC")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("unlockTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("ProjPlatinaSteam.Models.Jogo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioSteamId")
                        .HasColumnType("int");

                    b.Property<int>("gameHours")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("UsuarioSteamId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("ProjPlatinaSteam.Models.UsuarioSteam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("avatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("steamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsuariosSteam");
                });

            modelBuilder.Entity("ProjPlatinaSteam.Models.Conquista", b =>
                {
                    b.HasOne("ProjPlatinaSteam.Models.Jogo", "jogos")
                        .WithMany("conquistas")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("jogos");
                });

            modelBuilder.Entity("ProjPlatinaSteam.Models.Jogo", b =>
                {
                    b.HasOne("ProjPlatinaSteam.Models.UsuarioSteam", "UsuarioSteam")
                        .WithMany("jogos")
                        .HasForeignKey("UsuarioSteamId");

                    b.Navigation("UsuarioSteam");
                });

            modelBuilder.Entity("ProjPlatinaSteam.Models.Jogo", b =>
                {
                    b.Navigation("conquistas");
                });

            modelBuilder.Entity("ProjPlatinaSteam.Models.UsuarioSteam", b =>
                {
                    b.Navigation("jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
